spring:
  datasource:
    myconna:
      jdbc-url: 
      username: 
      password: 
      driverClassName: oracle.jdbc.driver.OracleDriver
    myconnb:
      jdbc-url: 
      username: 
      password: 
      driverClassName: oracle.jdbc.driver.OracleDriver
      
server:
  port: 8088

poolconfig:
  minimumIdle: 30
  maximumPoolSize: 30
  leakDetectionThreshold: 180000
  connectionTimeout: 300000
  validationTimeout: 3000
  idleTimeout: 600000
  maxLifetime: 1800000